steps:
  # ✅ Step 1: Build Docker image with cache optimization
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--cache-from'
      - 'gcr.io/$PROJECT_ID/servoya-cloud-worker:latest'
      - '-t'
      - 'gcr.io/$PROJECT_ID/servoya-cloud-worker:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/servoya-cloud-worker:latest'
      - '.'

  # ✅ Step 2: Push Docker image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/servoya-cloud-worker:$COMMIT_SHA'

  # ✅ Step 3: Deploy to Cloud Run with all environment variables
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'servoya-cloud-worker'
      - '--image'
      - 'gcr.io/$PROJECT_ID/servoya-cloud-worker:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '2Gi'
      - '--cpu'
      - '2'
      - '--timeout'
      - '300s'
      - '--concurrency'
      - '80'
      - '--max-instances'
      - '10'
      - '--set-env-vars'
      - 'NODE_ENV=production,OPENAI_API_KEY=$_OPENAI_API_KEY,ELEVENLABS_API_KEY=$_ELEVENLABS_API_KEY,SUPABASE_URL=$_SUPABASE_URL,SUPABASE_KEY=$_SUPABASE_KEY'

images:
  - 'gcr.io/$PROJECT_ID/servoya-cloud-worker:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/servoya-cloud-worker:latest'

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'

substitutions:
  _OPENAI_API_KEY: ''
  _ELEVENLABS_API_KEY: ''
  _SUPABASE_URL: ''
  _SUPABASE_KEY: ''
