steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/servoya-cloud-worker', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/servoya-cloud-worker']

images:
  - 'gcr.io/$PROJECT_ID/servoya-cloud-worker'
