steps:
  # Step 1: Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/servoya-cloud-worker:$COMMIT_SHA'
      - '.'

  # Step 2: Push Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/servoya-cloud-worker:$COMMIT_SHA']

  # Step 3: Deploy with longer timeout
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'servoya-cloud-worker'
      - '--image'
      - 'gcr.io/$PROJECT_ID/servoya-cloud-worker:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '1Gi'  # Reduced for faster startup
      - '--cpu'
      - '1'    # Reduced for faster startup
      - '--timeout'
      - '600s' # Increased timeout
      - '--set-env-vars'
      - 'NODE_ENV=production'

images:
  - 'gcr.io/$PROJECT_ID/servoya-cloud-worker:$COMMIT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'
