options:
  logging: CLOUD_LOGGING_ONLY

steps:
  - name: 'gcr.io/cloud-builders/npm'
    args: ['install', '--legacy-peer-deps']
    resources:
      limits:
        memory: '2Gi'

  - name: 'gcr.io/cloud-builders/npm'
    args: ['run', 'start']
    resources:
      limits:
        memory: '2Gi'

images:
  - 'gcr.io/$PROJECT_ID/servoya-cloud-worker'
