steps:
  # Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/servoya-worker:$COMMIT_SHA', '-t', 'gcr.io/$PROJECT_ID/servoya-worker:latest', '.']

  # Push both tags
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/servoya-worker:$COMMIT_SHA']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/servoya-worker:latest']

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      [
        'run','deploy','servoya-worker',
        '--image','gcr.io/$PROJECT_ID/servoya-worker:$COMMIT_SHA',
        '--platform','managed',
        '--region','us-central1',
        '--port','8080',
        '--allow-unauthenticated'
      ]

images:
  - 'gcr.io/$PROJECT_ID/servoya-worker:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/servoya-worker:latest'

timeout: '1200s'
