steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t',
      'gcr.io/servoya-cloud-worker/servoya-cloud-worker',
      '.'
    ]

  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push',
      'gcr.io/servoya-cloud-worker/servoya-cloud-worker'
    ]

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args: [
      'run',
      'deploy',
      'servoya-cloud-worker',
      '--image',
      'gcr.io/servoya-cloud-worker/servoya-cloud-worker',
      '--region',
      'us-central1',
      '--platform',
      'managed',
      '--allow-unauthenticated',
      '--memory',
      '2Gi',
      '--cpu',
      '2',
      '--timeout',
      '300s'
    ]

images:
  - 'gcr.io/servoya-cloud-worker/servoya-cloud-worker'
