steps:
  - name: 'gcr.io/cloud-builders/npm'
    args: ['ci', '--unsafe-perm']
  - name: 'gcr.io/cloud-builders/npm'
    args: ['run', 'start']
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'
timeout: '900s'
